replicaCount: 3

image:
  repository: chouroukchaker/frontenddevops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  - name: REACT_APP_SERVER_URL
    value: http://backend:5000  # ✅ NOM CORRECT DU SERVICE BACKEND

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mern-app.local
      paths:
        - path: /
          pathType: Prefix  # ✅ Requis pour Kubernetes >= 1.19
  tls: []  # Pas de certificat TLS

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
