replicaCount: 3

image:
  repository: chouroukchaker/frontenddevops  # 🛠 Assure-toi que cette image existe sur DockerHub !
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: MONGO_URI
    value: mongodb://mongodb:27017/Nouvelair
  - name: PORT
    value: "80"  # Port utilisé par le conteneur frontend (généralement 80 si c’est NGINX)
  - name: BACKEND_URL
    value: http://backend:5000  # Le nom du service backend dans Kubernetes

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mern-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Si tu veux activer HTTPS plus tard

serviceAccount:
  create: true
  name: ""

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
