replicaCount: 2

image:
  repository: chouroukchaker/frontenddevops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  - name: PORT
    value: "80"
  - name: BACKEND_URL
    value: http://backend:5000
  - name: MONGO_URI
    value: mongodb://mongodb:27017/Nouvelair

ingress:
  enabled: false

serviceAccount:
  create: true
  name: ""  