replicaCount: 1

image:
  repository: chouroukchaker/frontenddevops
  pullPolicy: IfNotPresent
  tag: latest

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}

env:
  - name: REACT_APP_SERVER_URL
    value: http://devop-backend:5000  # Corrige si ton service backend a un autre nom ou port

containerPort: 3000

imagePullSecrets: []
