replicaCount: 3

image:
  repository: chouroukchaker/backenddevops
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

env:
  - name: MONGO_URI
    value: mongodb://mongodb:27017/Nouvelair
  - name: PORT
    value: "5000"

ingress:
  enabled: false
